export const showLoader = 'APP/SHOW_LOADER'
export const hideLoader = 'APP/HIDE_LOADER'
export const showAlert = 'APP/SHOW_ALERT'
export const hideAlert = 'APP/HIDE_ALERT'
export const changeLanguage = 'APP/CHANGE_LANGUAGE'